source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

xcodeproj 'SimpleChat/SimpleChat.xcodeproj'

pod 'Starscream'
pod 'SwiftyJSON'
pod 'JSQMessagesViewController'
pod 'ChameleonFramework'
pod 'CocoaLumberjack/Swift'
