source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

xcodeproj 'SimpleChat/SimpleChat.xcodeproj'

pod 'Starscream', '~> 1.1.1'
pod 'SwiftyJSON'
pod 'JSQMessagesViewController'
pod 'JSQMessagesViewController'
pod 'ChameleonFramework'
