SET(STORED_CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_FIND_LIBRARY_SUFFIXES})
SET(CMAKE_FIND_LIBRARY_SUFFIXES .${CMAKE_SHARED_LIBRARY_SUFFIX} ${CMAKE_FIND_LIBRARY_SUFFIXES})

FIND_LIBRARY(VC100CRT_MSVCP_LIB msvcp100)

IF(NOT VC100CRT_MSVCP_LIB)
    MESSAGE(WARNING "Visual C++ redistributable library \"msvcp100\" not found")
ENDIF()

FIND_LIBRARY(VC100CRT_MSVCR_LIB msvcr100)

IF(NOT VC100CRT_MSVCR_LIB)
    MESSAGE(WARNING "Visual C++ redistributable library \"msvcr100\" not found")
ENDIF()

SET(CMAKE_FIND_LIBRARY_SUFFIXES ${STORED_CMAKE_FIND_LIBRARY_SUFFIXES})

MARK_AS_ADVANCED(
    VC100CRT_MSVCP_LIB
    VC100CRT_MSVCR_LIB
)

SET(
    VC100CRT_LIBRARIES
    ${VC100CRT_MSVCP_LIB}
    ${VC100CRT_MSVCR_LIB}
)
